In [1]:
from agent.agent import Agent
from functions import *
import sys

# if len(sys.argv) != 4:
#     print ("Usage: python train.py [stock] [window] [episodes]")
#     exit()

stock_name, window_size, episode_count = "^GSPC", 10 ,1000

agent = Agent(window_size)
data = getStockDataVec(stock_name)
l = len(data) - 1
batch_size = 32

for e in range(episode_count + 1):
    print ("Episode " + str(e) + "/" + str(episode_count))
    state = getState(data, 0, window_size + 1)

    total_profit = 0
    agent.inventory = []

    for t in range(l):
        action = agent.act(state)

        # sit
        next_state = getState(data, t + 1, window_size + 1)
        reward = 0

        if action == 1: # buy
            agent.inventory.append(data[t])
            print ("Buy: " + formatPrice(data[t]))

        elif action == 2 and len(agent.inventory) > 0: # sell
            bought_price = agent.inventory.pop(0)
            reward = max(data[t] - bought_price, 0)
            total_profit += data[t] - bought_price
            print("Sell: " + formatPrice(data[t]) + " | Profit: " + formatPrice(data[t] - bought_price))

        done = True if t == l - 1 else False
        agent.memory.append((state, action, reward, next_state, done))
        state = next_state

        if done:
            print ("--------------------------------")
            print ("Total Profit: " + formatPrice(total_profit))
            print ("--------------------------------")

        if len(agent.memory) > batch_size:
            agent.expReplay(batch_size)

    if e % 10 == 0:
        agent.model.save("models/model_ep" + str(e))


C:\Users\larsr\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


Episode 0/1000
(1, 10)
(1, 10)
(1, 10)
(1, 10)
(1, 10)
Buy: $1298.35
(1, 10)
Buy: $1295.86
(1, 10)
Buy: $1300.80
(1, 10)
Buy: $1313.27
(1, 10)
Sell: $1326.82 | Profit: $28.47
(1, 10)
(1, 10)
Buy: $1326.65
(1, 10)
Buy: $1329.47
(1, 10)
Sell: $1347.97 | Profit: $52.11
(1, 10)
(1, 10)
Buy: $1342.90
(1, 10)
(1, 10)
Sell: $1364.30 | Profit: $63.50
(1, 10)
(1, 10)
Sell: $1354.95 | Profit: $41.68
(1, 10)
Buy: $1364.17
(1, 10)
Buy: $1373.73
(1, 10)
(1, 10)
(1, 10)
Buy: $1349.47
(1, 10)
(1, 10)
Sell: $1352.26 | Profit: $25.61
(1, 10)
(1, 10)
Buy: $1332.53
(1, 10)
(1, 10)
Buy: $1330.31
(1, 10)
Sell: $1318.80 | Profit: -$10.67
(1, 10)
Sell: $1315.92 | Profit: -$26.98
(1, 10)
(1, 10)
Sell: $1301.53 | Profit: -$62.64
[[ 0.23376063  0.23012578 -0.45099413]]
[[-0.06938259  0.06244278 -0.34180936]]
[[-0.00374011  0.10447166 -0.27905598]]
[[-0.0478424  -0.10633655 -0.11668681]]
[[-0.09074933  0.40049803 -0.35423556]]
[[-0.25638255  0.44068238 28.64632   ]]
[[ 0.14365506  0.18070686 -0.5743123 ]]
[[ 0.1

[[1.2806317  0.81274873 1.3382763 ]]
[[-0.91948205  1.2248689   1.3673457 ]]
[[1.4105012  0.88648427 1.3045572 ]]
[[-1.1006936  1.0279669 64.83146  ]]
[[1.1739237  0.73595834 1.4351636 ]]
[[-0.6709025  0.7098344 42.805004 ]]
[[-0.8065821  1.3523088  1.2196491]]
[[-1.0249934  1.3444209  1.4591963]]
[[1.415869  0.8479701 1.4464856]]
[[0.91004163 1.1433829  1.5114017 ]]
[[-0.5542966  1.2501646  0.9772135]]
[[1.3260864  0.91756004 1.3375639 ]]
[[-0.79399186  0.89775556 26.842909  ]]
[[0.94021815 0.9619185  1.3093159 ]]
[[-0.51051223  0.85449564  1.0069609 ]]
[[1.2186286 0.6081451 0.9140006]]
[[-0.786698   0.90692    1.2867535]]
[[-0.538524    0.8043816   0.93206143]]
[[-0.32800883  0.58305264  0.84176207]]
[[0.70691603 0.8036394  0.88800085]]
[[-0.30171317  0.5689672   0.82928944]]
[[0.86516076 0.46924874 0.87860465]]
[[0.7387351  0.72099036 0.91098   ]]
[[0.66495657 0.7229846  0.77543086]]
[[-0.29164115  1.2076466   0.69749737]]
[[0.81537443 0.9196953  1.2643284 ]]
[[-0.352781    0.871212

[[10.260996  8.693541  9.344085]]
[[10.433582   7.6143713  9.79637  ]]
[[ 8.633672   8.9569645 11.044245 ]]
[[8.53066   7.3661795 9.128865 ]]
[[ 7.5026374 12.971192   9.02008  ]]
[[ 9.155497  11.1059265 13.706812 ]]
[[8.701203 8.247832 8.194884]]
[[ 7.9408236  7.126567  11.246667 ]]
[[11.161152  7.985682 11.869108]]
[[11.693411   7.0934377  8.424281 ]]
[[15.388716  9.91617  12.339313]]
[[14.0057745 16.334536  16.236532 ]]
[[18.625341 14.085389 17.247763]]
[[17.449774 19.229956 19.66967 ]]
[[18.59015  16.554966 16.67675 ]]
[[19.905754 14.237669 17.596212]]
(1, 10)
Buy: $1197.66
[[19.567663 20.635014 21.434387]]
[[19.176615 20.096552 21.796705]]
[[20.181902 17.527735 21.189735]]
[[17.799452 18.105656 21.278452]]
[[17.217794 18.73878  18.762945]]
[[19.301758 16.455696 19.783058]]
[[19.127949 17.678492 41.55438 ]]
[[15.257431 14.352081 16.983908]]
[[14.882224 14.462862 16.260664]]
[[15.616244 13.056061 15.328978]]
[[16.041788 13.098405 16.546982]]
[[12.211551 12.220633 13.253674]]
[[14.006

[[17.60869  18.558607 17.439445]]
[[18.2964   14.914773 16.961573]]
[[17.653769 16.934048 17.804905]]
[[18.554667 15.532682 16.79342 ]]
[[15.087299 14.647449 16.235706]]
[[13.873955 15.070351 15.850802]]
[[14.324989 11.75957  13.080716]]
[[13.27767  17.405836 15.048101]]
[[13.520114 17.389677 18.300013]]
[[14.148522 13.219536 12.084223]]
[[12.339937 12.000946 15.652615]]
[[16.204441 13.381094 16.452532]]
[[18.882244 12.140168 13.2515  ]]
[[22.130262 17.131695 18.839525]]
[[20.90885  24.305319 23.283737]]
[[28.364239 22.010077 24.298906]]
[[28.578749 27.090681 29.899145]]
[[28.294182 26.395031 26.22728 ]]
[[29.134989 23.403421 25.927385]]
[[28.367    28.624853 30.66869 ]]
[[29.69573  28.28353  30.122692]]
[[27.016434 27.777048 29.774979]]
[[26.751848 26.810064 24.913935]]
[[24.71343  22.559313 24.798992]]
[[20.316462 24.724796 25.949068]]
[[21.253532 18.56378  18.924097]]
[[19.79939  19.628191 19.198687]]
[[24.54386  19.632689 20.614319]]
(1, 10)
Buy: $1152.69
[[21.180859 18.48597  19.8

[[19.003029 17.587574 20.737501]]
[[17.336403 17.192577 18.489407]]
[[18.21329  15.89395  20.926783]]
[[22.002176 19.768953 21.536642]]
[[20.553207 18.027487 20.814093]]
[[18.06101  17.862797 15.979834]]
[[14.557361 16.299072 16.331657]]
model predicts [[17.168386 15.214081 16.582466]] 0
(1, 10)
[[11.864581  9.438644 10.744091]]
[[10.241829 13.332875 12.472211]]
[[10.331898  13.6553335 14.016125 ]]
[[10.810984 10.215646  9.91792 ]]
[[10.088743  9.916438 11.963223]]
[[11.914323 13.448324 12.580722]]
[[16.001019  9.639504 11.244735]]
[[17.9025   14.129492 15.619878]]
[[16.65821  20.85898  18.844168]]
[[23.05091  17.609362 19.773348]]
[[23.268482 21.108492 24.297567]]
[[21.964882 20.634787 21.970636]]
[[24.261257 19.2221   21.374077]]
[[23.779428 22.282713 25.54733 ]]
[[22.584705 22.279016 23.441158]]
[[20.129824 22.250689 23.43897 ]]
[[18.482939 20.431225 19.173313]]
[[19.11453  17.55937  19.262293]]
[[15.774466 19.631668 20.085314]]
[[16.561869 14.659274 14.7653  ]]
[[14.928178 16.97624

[[12.6      14.682709 14.19888 ]]
[[14.1140995 13.888328  14.886563 ]]
[[12.801433 14.6626   14.842689]]
[[13.653671 16.945951 15.422109]]
[[18.77559  16.009033 17.3621  ]]
[[19.33666  13.940064 16.175678]]
[[19.854794 19.0005   20.364973]]
[[22.605013 16.7994   18.788456]]
[[23.846472 18.168253 23.51905 ]]
[[22.65337  23.902712 24.804188]]
model predicts [[23.633516 22.213707 23.904682]] 2
(1, 10)
Sell: $1253.69 | Profit: $86.98
[[22.271845 16.617558 18.995472]]
[[23.554628 21.088043 23.226027]]
[[22.29755  19.41759  22.137598]]
[[22.733095 18.36844  20.711742]]
[[23.630545 20.334692 23.968716]]
[[21.459694 19.540007 21.17467 ]]
[[18.27616  19.616959 20.57426 ]]
[[16.741333 18.618853 17.59717 ]]
[[17.874735 16.35765  17.865715]]
[[15.172089 18.371649 18.795124]]
[[15.943852 13.425681 14.267306]]
[[14.413461 17.129347 15.001969]]
[[17.758638 14.66075  16.358952]]
[[17.404829 17.72972  18.697153]]
[[17.910257 16.69396  18.658318]]
[[17.962658 16.302828 17.569603]]
[[18.894556 15.366239 

[[276.31516 238.53902 265.251  ]]
[[274.56775 299.62674 294.22983]]
[[302.1503 281.8353 319.3087]]
[[261.8742  275.14948 299.81088]]
[[264.98462 253.53143 309.39417]]
[[307.44562 283.7942  329.08066]]
[[284.59906 257.71606 300.9486 ]]
[[250.87746 251.9214  253.4372 ]]
[[245.23251 247.291   281.35364]]
[[241.3524  273.42822 297.45618]]
[[231.60474 251.23273 254.16934]]
[[240.45473 281.50964 264.80737]]
[[277.3925 274.7134 297.6143]]
[[319.71786 268.99518 293.17172]]
[[305.32602 314.5664  338.80283]]
[[338.2145  298.06732 323.39093]]
[[329.23175 332.44025 399.59424]]
[[423.3733  395.41205 425.80203]]
[[417.4076  418.2351  476.17807]]
[[383.4546  376.02457 416.37784]]
[[375.4369  369.06427 437.10855]]
[[361.79483 325.49316 353.47617]]
[[365.83548 392.19244 387.4568 ]]
[[410.43552 386.45337 420.4933 ]]
[[415.1731 402.3742 489.8184]]
[[419.6094  383.41858 419.1689 ]]
[[432.91223 439.76282 451.4078 ]]
(1, 10)
[[311.7604  355.3998  389.42838]]
[[322.0307  302.7184  280.48837]]
[[282.1636  348

[[618.30084 604.17596 656.9755 ]]
[[551.8109  473.47833 558.43384]]
[[490.23325 479.08203 628.61066]]
(1, 10)
Buy: $1248.92
[[679.22095 632.30615 689.76715]]
[[665.1624 586.1831 667.2007]]
[[605.59894 590.73944 555.1466 ]]
[[574.0651 557.0864 575.5394]]
[[496.88028 576.7866  605.20294]]
[[510.98886 521.6258  521.7527 ]]
[[535.3184  574.65704 547.74524]]
[[590.9005 575.5005 604.2691]]
[[653.1389  588.5622  621.54297]]
[[637.0009  655.8673  687.44495]]
[[713.25214 634.9499  670.0726 ]]
[[734.86426 714.52167 820.80035]]
[[839.6884 823.8134 866.333 ]]
[[865.3424 841.4906 875.3697]]
[[807.9443  738.61707 831.2912 ]]
[[761.5966  736.34015 739.596  ]]
[[710.84045 631.5613  665.13837]]
[[733.6011  718.88715 748.25684]]
[[760.306   719.07367 756.94366]]
[[783.3429  757.87775 778.87726]]
[[721.1043  676.7292  713.97015]]
[[747.6249  737.62805 759.29   ]]
[[717.80457 734.9754  777.2156 ]]
[[750.4343 789.9038 755.3502]]
[[815.9989  789.90753 845.33374]]
[[796.5323  758.62836 785.47345]]
[[703.9535

[[1266.8138 1094.7311 1254.9143]]
[[1152.9258 1072.5099 1063.8029]]
[[1074.807    943.36975  998.35675]]
[[1132.9606 1099.621  1114.7233]]
[[1153.5588 1086.1956 1150.0999]]
[[1215.8588 1126.9321 1130.1036]]
[[1100.1196 1007.058  1067.671 ]]
[[1158.8667 1158.6837 1135.0488]]
[[1120.4501 1128.9589 1196.6064]]
[[1177.1644 1191.7529 1146.8242]]
[[1254.0144 1170.8076 1230.3618]]
[[1205.7363 1114.8995 1133.6091]]
[[1083.6562  1018.15063  996.91846]]
[[925.83844 871.90137 921.3768 ]]
[[834.54095 725.8302  819.68115]]
[[762.26447 719.62476 878.6243 ]]
[[810.4452  755.9589  798.29535]]
[[905.4283 754.1332 784.6228]]
[[995.0264  893.9945  932.72296]]
[[1050.4801  992.6852 1190.7378]]
[[1211.202 1128.711 1368.633]]
[[1384.2094 1299.3934 1354.1395]]
[[1385.0854 1289.4972 1277.4907]]
[[1327.251  1207.2173 1264.5728]]
[[1209.2416 1314.5074 1378.928 ]]
(1, 10)
[[1010.9251 1035.2491 1084.1962]]
[[1139.6869   986.79895 1038.8257 ]]
[[1197.3167 1132.455  1278.2311]]
[[1319.725  1273.2776 1338.1846]]
[[1

[[ 839.53394  984.11914 1002.41766]]
[[693.9001  867.83984 883.8369 ]]
[[695.4471  717.87976 583.5245 ]]
[[636.8746 589.7513 598.5284]]
[[640.5664  657.99365 730.02924]]
[[725.90564 748.6539  760.8955 ]]
[[767.89954 856.846   800.14197]]
[[865.60956 833.1177  901.89154]]
[[850.4462  859.02185 930.8427 ]]
(1, 10)
Buy: $1276.96
[[781.042   815.243   813.48505]]
[[855.41797 846.6894  858.1646 ]]
[[862.70715 886.34924 884.5045 ]]
[[858.1198 813.0737 825.6331]]
[[867.6518  906.7908  904.15967]]
[[818.72345 939.9611  955.3942 ]]
[[831.29456 886.2495  861.6068 ]]
[[889.30994 919.9771  901.56854]]
[[828.6404 845.5645 844.8528]]
[[742.34094 770.7399  738.67267]]
[[622.3076  648.25574 697.7737 ]]
[[573.02435 520.862   600.4548 ]]
[[521.0095 541.7835 682.8201]]
[[575.47675 602.67426 605.2509 ]]
[[718.0286  627.25635 634.65344]]
[[816.9155  744.99615 756.70374]]
[[821.4031 850.0927 958.1789]]
[[ 929.8537   946.61597 1096.0098 ]]
[[1045.6742 1074.1655 1020.7593]]
[[ 991.5596  1008.86475  945.57184]

[[674.19965 689.37354 713.2456 ]]
[[600.5196 626.3297 618.3326]]
[[493.4686 516.8894 588.9374]]
[[456.7573  428.22882 485.42056]]
[[421.79364 440.0825  596.75793]]
[[482.33508 522.4878  514.1616 ]]
[[633.4381  536.99365 549.9272 ]]
[[708.4063 648.4681 667.1086]]
[[703.17725 727.6101  828.6021 ]]
[[788.68097 801.13293 934.27997]]
[[870.3601  893.8028  844.58777]]
[[802.4237  815.59784 765.13654]]
[[761.84796 720.8885  741.5817 ]]
[[665.737  780.1674 802.5739]]
[[552.5593  681.43286 700.7524 ]]
[[542.2968  566.77167 473.9723 ]]
[[538.9665 472.6054 484.3297]]
[[533.6952 551.5493 630.8594]]
[[616.6713  639.491   667.83636]]
[[665.1576 755.7026 702.891 ]]
[[753.8939 716.7967 795.8898]]
[[723.4279  730.25574 778.2778 ]]
[[770.2385 683.891  816.3072]]
[[684.6499  697.09283 594.343  ]]
[[589.8665  648.11554 624.0694 ]]
[[562.8308 662.9734 681.036 ]]
[[560.39777 573.7675  483.26514]]
[[390.787   494.65366 507.11435]]
[[322.52737 399.0589  409.8585 ]]
[[437.94968 329.42264 338.29205]]
[[432.6989

KeyboardInterrupt: 

In [ ]:
data